spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=UTC-7
    username: demo
    password: admin

server:
  port: 8081